---
#registry config
registry_name: DATA+OMITTED
auth:
  - login: DATA+OMITTED
    password: DATA+OMITTED
  - login: DATA+OMITTED
    password: DATA+OMITTED
auth_file: DATA+OMITTED
path:
  certificate: DATA+OMITTED
  authentication: DATA+OMITTED

# k8s config
kube_config_local_path: DATA+OMITTED
master: DATA+OMITTED
subnet: DATA+OMITTED

# Fabric
fabric_profile: fabric-v1model

onos_applications:
  - name: org.onosproject.drivers.bmv2
  - name: org.stratumproject.fabric-tna
  - name: org.onosproject.lldpprovider
  - name: org.onosproject.hostprovider

netcfg:
  devices:
    "device:sopnode-sw1":
      basic:
        managementAddress: "grpc://10.255.255.3:9559?device_id=1"
        driver: "stratum-tofino"
        pipeconf: "org.stratumproject.fabric.mavericks_sde_9_7_0"
        locType: "grid"
        gridX: 200
        gridY: 600
    "device:sopnode-sw2":
      basic:
        managementAddress: "grpc://10.255.255.4:9559?device_id=1"
        driver: "stratum-tofino"
        pipeconf: "org.stratumproject.fabric.montara_sde_9_7_0"
        locType: "grid"
        gridX: 400
        gridY: 400