---
- name: Install stratum node
  hosts: switches
  #roles:
  #  - role: container
  tasks:
    - name: Retrieve stratum
      become: yes
      ansible.builtin.git:
        repo: https://github.com/stratum/stratum.git
        dest: ./stratum/
        version: e2640fc
        force: yes
    - name: copying the chassis_config_file
      copy: 
        dest: ./stratum/stratum/hal/bin/bmv2
        src: ./chassis_config.pb.txt
        force: yes
    - name: change docker permissions
      become: yes
      shell: "chmod 666 /var/run/docker.sock"
    - name: starting the stratum container
      shell: "./stratum/setup_dev_env.sh -- --privileged -d --network=host --name stratum-container"
    - name: Check if stratum already been built
      stat:
        path: ./stratum/stratum_bmv2_deb.deb
      register: stat_result
    - name: building stratum if its not already built
      become: yes
      shell: "docker exec stratum-container bazel build //stratum/hal/bin/bmv2:stratum_bmv2_deb"
      when:  not stat_result.stat.exists
    - name: coppying the builded stratum package
      become: yes
      shell: "docker exec stratum-container cp -f /stratum/bazel-bin/stratum/hal/bin/bmv2/stratum_bmv2_deb.deb /stratum/"
      when: not stat_result.stat.exists
    - name: apt-update
      become: yes
      shell: "docker exec stratum-container sudo apt-get update"
    - name: installing stratum
      become: yes
      shell: "docker exec stratum-container sudo apt-get install -y --reinstall ./stratum_bmv2_deb.deb"
    - name: strating stratum with the chassis
      become: yes
      shell: "docker exec -d stratum-container sudo stratum_bmv2 -chassis_config_file=/etc/stratum/chassis_config.pb.txt"




    
