---
- name: Remove unstable ONL APT repo
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/multistrap-onl.list
    state: absent

- name: Install dependencies (system)
  ansible.builtin.apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    autoclean: yes
    update_cache: true
  with_items: "{{ debian_dependencies }}"

- name: Install dependencies (Python)
  ansible.builtin.pip:
    name: "{{ item.name }}=={{ item.version }}"
  with_items: "{{ python_packages }}"

- name: Setting hugepages
  ansible.posix.sysctl:
    name: vm.nr_hugepages
    value: "128"
    state: present

- name: Mount hugepage
  ansible.posix.mount:
    name: /mnt/huge
    src: nodev
    fstype: hugetlbfs
    opts: "pagesize=1GB"
    state: mounted

- name: Disable swap
  shell: swapoff -a 