---
- name: Install kernel extra
  ansible.builtin.shell: dnf install -y kernel-modules-extra-`uname -r`

- name: Load SCTP
  ansible.builtin.shell: modprobe sctp

- name: Set dependencies
  set_fact:
    dependencies:
      system: "{{ lookup('vars', (ansible_distribution | lower)+ '_'+ (ansible_distribution_major_version) +'_dependencies')}}"
      python: "{{ python_packages }}"