# Docker

# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- develop

pool:
 name: Default
 #name: Azure Pipelines
 
resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'


stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: Default

    steps:
    - task: DockerInstaller@0
      inputs:
        dockerVersion: 'latest'
    - script:
        docker build -t blueprint ./sopnode/ansible/Dockerfile
      displayName: Build an image
      
