

# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- develop

pool:
 name: Default
 #name: Azure Pipelines
 
resources:
- repo: self



stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: Default

    steps:

    - task: DockerInstaller@0
      inputs:
        dockerVersion: '17.09.0-ce'
      displayName: Install docker
        # Docker
    - task: Docker@2
      inputs:
        containerRegistry: 'dockeregistry'
        repository: 'anassdahchour/blueprint'
        command: 'buildAndPush'
        Dockerfile: 'sopnode/ansible/Dockerfile'
    - script: | 
              whoami  
              apt update && apt install -y python3-pip git
              python3 -m pip install --user ansible-core==2.13.2
              echo "export PATH=$PATH:~/.local/bin" >> ~/.bashrc
              mkdir /reqs/
              cp collections/requirements.yml /reqs/ansible-galaxy.yml
              cp requirements.txt /reqs/python3.txt
              ~/.local/bin/ansible-galaxy install -r /reqs/ansible-galaxy.yml
              pip3 install -r /reqs/python3.txt
              git checkout tags/2nd-summer-school
              cd sopnode/ansible
              #docker run -it -v "$(pwd)":/blueprint -v ${HOME}/.ssh/id_rsa_blueprint:/id_rsa_blueprint blueprint
              ansible-playbook  -i inventories/blueprint/ k8s-master.yaml --extra-vars "@params.blueprint.yaml"

      displayName: Install dependencies
