

# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- develop

pool:
 name: Default
 #name: Azure Pipelines
 
resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'


stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: Default

    steps:

    - task: DockerInstaller@0
      inputs:
        dockerVersion: '17.09.0-ce'
      displayName: Install docker
        # Docker
    - task: Docker@2
      inputs:
        repository: 'docker.io/anassdahchour /blueprintest'
        command: 'buildAndPush'
        Dockerfile: 'Dockerfile'
        buildContext: 'sopnode/ansible/'  
      displayName: build image
