

# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- develop

pool:
 name: Default
 #name: Azure Pipelines
 
resources:
- repo: self




stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: Default

    steps:
    # - task: SSH@0
    #   inputs:
    #     sshEndpoint: 'ssh-sop'
    #     runOptions: 'commands'
    #     commands: |
    #       ssh -A interns@sopnode-z1.inria.fr "multipass launch --name test"
    #     readyTimeout: '20000'
    
    - task: SSH@0
      inputs:
        sshEndpoint: 'ssh-sop'
        runOptions: 'commands'
        commands: |
          ssh -A interns@sopnode-z1.inria.fr "papa=lol && echo \$papa"
        readyTimeout: '20000'


    - script: |

        # Setup Environment
        export PATH="$HOME/.local/bin:$PATH"
        . ~/.bashrc
        git checkout tags/2nd-summer-school
        cd sopnode/ansible
      #   # Creating RAN cluster
      #   sed -i 's/172\.16\.2\.2/10\.92\.171\.134/g' inventories/blueprint/ran/hosts
      #   sed -i 's/root/ubuntu/g' inventories/blueprint/ran/group_vars/all
      #   sed -i 's/172\.16\.2\.27/10\.92\.171\.134/g; s/172\.16\.0\.0\/12/10\.92\.171\.0\/24/g' params.blueprint.ran.yaml 
      #   ansible-playbook -i inventories/blueprint/ran/ k8s-master.yaml --extra-vars "@params.blueprint.ran.yaml"
      #   ansible-playbook -i inventories/blueprint/ran/ k8s-node.yaml --extra-vars "@params.blueprint.ran.yaml"


      #   # Creating Core cluster
      #   sed -i 's/root/ubuntu/g' inventories/blueprint/core/group_vars/all
      #   sed -i 's/172\.16\.2\.26/10\.92\.171\.140/g; s/172\.16\.0\.0\/12/10\.92\.171\.0\/24/g' params.blueprint.core.yaml
      #   sed -i 's/172\.16\.2\.5/10\.92\.171\.140/g; s/172\.16\.2\.6/10\.92\.171\.229/g' inventories/blueprint/core/hosts
      #   ansible-playbook -i inventories/blueprint/core/ k8s-master.yaml --extra-vars "@params.blueprint.core.yaml"
      #   ansible-playbook -i inventories/blueprint/core/ k8s-nodes.yaml --extra-vars "@params.blueprint.core.yaml"
    # - task: SSH@0
    #   inputs:
    #     sshEndpoint: 'ssh-sop'
    #     runOptions: 'commands'
    #     commands: 'ssh -A interns@sopnode-z1.inria.fr "multipass delete --purge test"'
    #     readyTimeout: '20000'
      # displayName: Ansible deploy
    # - task: DockerInstaller@0
    #   inputs:
    #     dockerVersion: '17.09.0-ce'
    #   displayName: Install docker
    #     # Docker
    # - task: Docker@2
    #   inputs:
    #     containerRegistry: 'dockeregistry'
    #     repository: 'anassdahchour/blueprint'
    #     command: 'buildAndPush'
    #     Dockerfile: 'sopnode/ansible/Dockerfile'
    # - script: | 

    #           # git checkout tags/2nd-summer-school
    #           cd sopnode/ansible
    #   displayName: check dependencies
    # - script: |
    #           python3 -m pip -V
    #           echo $PATH

    #           ansible --version
    #           #ansible-playbook  -i inventories/blueprint/ k8s-master.yaml --extra-vars "@params.blueprint.yaml"
    #   displayName: Ansible