

# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- develop

pool:
 name: Default
 #name: Azure Pipelines
 
resources:
- repo: self

variables:
  setup_script: &setup_script |
    export PATH="$HOME/.local/bin:$PATH"
    . ~/.bashrc
    git checkout tags/2nd-summer-school
    cd sopnode/ansible



stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: Default

    steps:
    - script: *setup_script  # Reference the setup_script anchor
      displayName: Setup Environment
    # - script: |
    #           export PATH="$HOME/.local/bin:$PATH"
    #           . ~/.bashrc
    #           git checkout tags/2nd-summer-school
    #           cd sopnode/ansible
    #   displayName: Adding ansible to path
    #   name: setup_environment
    - script: |
              sed -i 's/172\.16\.2\.2/10\.92\.171\.134/g' inventories/blueprint/ran/hosts
              sed -i 's/root/ubuntu/g' inventories/blueprint/ran/group_vars/all
              sed -i 's/172\.16\.2\.27/10\.92\.171\.134/g; s/172\.16\.0\.0\/12/10\.92\.171\.0\/24/g' params.blueprint.ran.yaml 
              ansible-playbook  -i inventories/blueprint/ran/ k8s-master.yaml --extra-vars "@params.blueprint.ran.yaml"
      displayName: Creating RAN cluster
    - script: |
              #core
              sed -i 's/root/ubuntu/g' inventories/blueprint/core/group_vars/all
              sed -i 's/172\.16\.2\.26/10\.92\.171\.140/g; s/172\.16\.0\.0\/12/10\.92\.171\.0\/24/g' params.blueprint.core.yaml
              sed -i 's/172\.16\.2\.5/10\.92\.171\.140/g; s/172\.16\.2\.6/10\.92\.171\.229/g' inventories/blueprint/core/hosts
      displayName: Creating Core cluster
    # - task: DockerInstaller@0
    #   inputs:
    #     dockerVersion: '17.09.0-ce'
    #   displayName: Install docker
    #     # Docker
    # - task: Docker@2
    #   inputs:
    #     containerRegistry: 'dockeregistry'
    #     repository: 'anassdahchour/blueprint'
    #     command: 'buildAndPush'
    #     Dockerfile: 'sopnode/ansible/Dockerfile'
    # - script: | 

    #           # git checkout tags/2nd-summer-school
    #           cd sopnode/ansible
    #   displayName: check dependencies
    # - script: |
    #           python3 -m pip -V
    #           echo $PATH

    #           ansible --version
    #           #ansible-playbook  -i inventories/blueprint/ k8s-master.yaml --extra-vars "@params.blueprint.yaml"
    #   displayName: Ansible