---
kernel:
  modules:
    - 'overlay'
    - 'br_netfilter'
    - 'zozo'
  attributes:
    - option: net.bridge.bridge-nf-call-ip6tables
      value: 1
    - option: net.bridge.bridge-nf-call-iptables
      value: 1
    - option: net.ipv4.ip_forward
      value: 1