---
kernel:
  modules:
    - 'overlay'
    - 'br_netfilter'
  attributes:
    - option: net.bridge.bridge-nf-call-ip6tables
      value: 1
    - option: net.bridge.bridge-nf-call-iptables
      value: 1
    - option: net.ipv4.ip_forward
      value: 1

k8s_tools:
  - kubectl=1.25.2-00
  - kubeadm=1.25.2-00
  - kubelet=1.25.2-00

k8s_tools_OLD:
  - kubectl=1.23.7-00
  - kubeadm=1.23.7-00
  - kubelet=1.23.7-00