- name: Create authentication directory
  ansible.builtin.file:
    path: auths
    state: directory

- name: Copy authentication file
  ansible.builtin.copy:
    src:  '{{ auths_file }}'
    dest: auths/htpasswd
    mode: '0600'
  when: auths_file is defined

- name: Create authentication file
  ansible.builtin.file:
    path: auths/htpasswd
    state: touch
    mode: '0600'
  when: auths_file is not defined

- name: random image name
  set_fact:
    htpasswd_image_name: "{{ lookup( 'password', '/dev/null length=32' ) | to_uuid }}"
  when: auths is defined

- name: uuid
  debug:
    var: htpasswd_image_name

- name: copy Dockerfile
  ansible.builtin.copy:
    src: Dockerfile
    dest: auths/Dockerfile
  when: auths is defined

- name: Build the htpasswd generator
  community.docker.docker_image:
    build:
      path: auths
    name: '{{ htpasswd_image_name }}'
    source: build
  when: auths is defined

- name: Add users to the authentication file
  shell: docker run --rm {{ htpasswd_image_name }} {{ item.login }} {{ item.password }} >> htpasswd
  args:
    chdir: auths
  with_items: "{{ auths }}"
  loop_control:
    label: "{{ item.login }}"
  when: auths is defined

- name: Cleanup the image
  community.docker.docker_image:
    state: absent
    name: '{{ htpasswd_image_name }}'
  when: auths is defined