---
- name: Add k8s APT key
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add k8s repository into sources list
  ansible.builtin.apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    update_cache: true

- name: Install k8s tools
  ansible.builtin.apt:
    name: '{{ item }}'
    allow_downgrade: yes
    autoclean: yes
    state: present
  with_items: '{{ k8s_tools }}'

- name: Create /var/lib/kubelet/ directory
  ansible.builtin.file:
    path: /var/lib/kubelet/
    state: directory

- name: Create /etc/kubernetes/manifests directory
  ansible.builtin.file:
    path: /etc/kubernetes/manifests
    state: directory