---
# Dependencies for k8s
- include_tasks: setup.yaml

# Install k8s
- name: Install k8s tools
  ansible.builtin.apt:
    name: '{{ item }}'
    autoclean: yes
    state: present
  with_items: '{{ k8s_tools }}'

- name: Create a symbolic link /run/systemd/resolve -> /run/resolvconf/
  ansible.builtin.file:
    src: /run/resolvconf/ 
    dest: /run/systemd/resolve
    state: link
  when: ansible_distribution == 'Debian' and ansible_distribution_major_version == 9
- name: Create ~/.kube
  ansible.builtin.file:
    path: ~/.kube/
    state: directory
- name: Create /var/lib/kubelet/ directory
  ansible.builtin.file:
    path: /var/lib/kubelet/
    state: directory
- name: Create /etc/kubernetes/manifests directory
  ansible.builtin.file:
    path: /etc/kubernetes/manifests
    state: directory

#- name: Prepare kubeadm
#  ansible.builtin.lineinfile:
#    path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
#    regexp: '(?!.*?--cgroup-driver=cgroupfs)^Environment="KUBELET_CONFIG_ARGS=(.*)"$'
#    backrefs: yes
#    line: 'Environment="KUBELET_CONFIG_ARGS=--cgroup-driver=cgroupfs \1"'

- name: Reset k8s
  shell: "kubeadm reset -f {{ k8s.kubeadm_options | default('')}}"

- name: Install helm (1/2)
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: '0555'

- name: Install helm (2/2)
  shell: "/tmp/get_helm.sh"