---
- name: Check if OS is SONiC
  stat:
    path: /etc/sonic/sonic_release
  register: is_SONiC_os

- name: SONiC specific actions
  block:
    - name: "Banner"
      debug:
        msg: 'We are SONiC'
  when: is_SONiC_os.stat.exists