---
- name: Check if OS is SONiC
  stat:
    path: /etc/sonic/sonic_release
  register: is_SONiC_os

- name: install stuff
  block:

  - name: Add kenel modules (1/2)
    lineinfile:
      path: "/etc/modules-load.d/k8s.conf"
      regexp: '^{{ item }}'
      line:  "{{ item }}"
      state: present
      create: true
      mode: '0644'
    with_items: "{{ kernel.modules }}"

  - name: Configure kernel attributes (1/2)
    lineinfile:
      path: "/etc/sysctl.d/k8s.conf"
      regexp: '^{{ item.option }}\s*='
      line:  '{{ item.option }} = {{ item.value }}'
      state: present
      create: true
      mode: '0644'
    with_items: "{{ kernel.attributes }}"

  when: is_SONiC_os.stat.exists

