- name: Initialize the master node
  shell: 'kubeadm init --pod-network-cidr={{ subnet }} --upload-certs'
  register: kubeadm_init

- name: Set Calico installation instructions
  ansible.builtin.template:
    src: calico.yaml.j2
    dest: calico.yaml

- name: Install Calico
  shell: kubectl create -f calico.yaml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

# XXX: should make a loopback to be cleaner
- name: Impose Calico to use admin interface for IP_AUTODETECTION_METHOD
  shell: 'kubectl set env daemonset/calico-node -n kube-system IP_AUTODETECTION_METHOD=interface=ma1'
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf