- name: Create kubeadm configuration
  ansible.builtin.template:
    src: kubeadm_config.yaml.j2
    dest: ./kubeadm_config.yaml

- name: Initialize the master node
  shell: 'kubeadm init --upload-certs --config kubeadm_config.yaml'
  register: kubeadm_init

#- name: Initialize the master node  (automatic address)
#  shell: 'kubeadm init --pod-network-cidr={{ k8s.subnet }} --upload-certs {{ k8s.kubeadm_options | default("")}}'
#  register: kubeadm_init
#  when: "'apiserver_advertise_address' not in k8s"

#- name: Initialize the master node (force address)
#  shell: 'kubeadm init --pod-network-cidr={{ k8s.subnet }} --upload-certs --apiserver-advertise-address={{ k8s.apiserver_advertise_address }} {{ k8s.kubeadm_options | default("")}}'
#  register: kubeadm_init
#  when: "'apiserver_advertise_address' in k8s"
  
- name: Create a symbolic link /etc/kubernetes/admin.conf -> ~/.kube/config
  ansible.builtin.file:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    state: link

#- name: Set Calico installation instructions
#  ansible.builtin.template:
#    src: calico.yaml.j2
#    dest: calico.yaml
#
#- name: Install Calico
#  shell: kubectl create -f calico.yaml
#  environment:
#    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Create tigera-operator namespace 
  kubernetes.core.k8s:
    name: tigera-operator
    api_version: v1
    kind: Namespace
    state: present

- name: Set Calico installation instructions
  ansible.builtin.template:
    src: tigera_operator.yaml.j2
    dest: tigera_operator.yaml

- name: Register project-calico helm repo
  shell: 'helm repo add projectcalico https://projectcalico.docs.tigera.io/charts'

- name: Install Calico
  shell: 'helm install calico projectcalico/tigera-operator --version v3.24.1 -f tigera_operator.yaml --namespace tigera-operator'