---
- block:
  - include_tasks: "{{ 'cri-o_' + (ansible_distribution | lower) + '.yaml' }}"

  - name: Enable and start cri-o service
    ansible.builtin.systemd:
      name: crio
      state: started
      enabled: yes
  become: yes