---
- name: Load secrets
  ansible.builtin.include_vars:
    file: secrets.yaml

- name: Load network database from Netbox
  local_action: ansible.builtin.shell python3 roles/network/files/netbox_db.py --port {{ netbox_port}} --server {{ netbox_server}} --token {{ netbox_token }}
  register: db

- name: Store netbox database
  ansible.builtin.set_fact:
    db: "{{ db.stdout | from_yaml }}"

- name: Configure and launch ISC DHCPD
  block:
    - name: Create DHCPD.conf
      ansible.builtin.template:
        src: dhcpd.j2
        dest: /root/dhcpd/dhcpd.conf

    - name: Start ISC DHCPD
      community.docker.docker_container:
        name: dhcpd
        image: networkboot/dhcpd
        volumes:
          - /root/dhcpd/:/data
        networks:
          - name: host
        restart_policy: unless-stopped
        restart: true

  when: inventory_hostname in groups.dhcpd

- name: Create interface aliases
  # ansible.builtin.shell: 'ip link property add dev {{ item.1 }} altname {{ item.0.ifname }}'
  ansible.builtin.debug:
    msg: '{{ item.0.device_name }}: ip link property add dev {{ item.1 }} altname {{ item.0.ifname }}'
  when: ansible_facts[item.1]['macaddress']|default(None) == item.0.mac and item.1 != item.0.ifname
  ignore_errors: true
  with_nested:
  - '{{ db.devices[inventory_hostname_short].interfaces }}'
  - '{{ ansible_interfaces }}'