---
- name: Load secrets
  ansible.builtin.include_vars:
    file: secrets.yaml

- name: Determine network interface aliases
  local_action: ansible.builtin.shell python3 roles/network/files/create_aliases.py --port {{ netbox_port}} --server {{ netbox_server}} --token {{ netbox_token }}
  register: iface_aliases

- name: Set variables
  ansible.builtin.set_fact:
    iface_aliases: "{{ iface_aliases.stdout | from_yaml | list }}"

- name: Create interface aliases
  ansible.builtin.shell: 'ip link property add dev {{ item.1 }} altname {{ item.0.interface.ifname }}'
  # ansible.builtin.debug:
  #   msg: '{{ item.0.name }}: ip link property add dev {{ item.1 }} altname {{ item.0.interface.ifname }}'
  when: inventory_hostname_short == item.0.name and ansible_facts[item.1]['macaddress']|default(None) == item.0.interface.mac
  ignore_errors: true
  with_nested:
  - '{{ iface_aliases }}'
  - '{{ ansible_interfaces }}'