---
# Stratum
stratum:
  mode: bmv2 

# Fabric
fabric:
  profile: fabric-v1model

k8s:
  subnet: 10.244.0.0/16
  apiserver-advertise-address: 192.168.34.2

# calico config
calico:
  IP_AUTODETECTION_METHOD: interface=eth1

# ONOS
onos:
  image: onosproject/onos:2.5.8
  mode:  docker
  applications:
    - name: org.onosproject.drivers.barefoot
    - name: org.onosproject.drivers.bmv2
    - name: org.onosproject.lldpprovider
    - name: org.onosproject.hostprovider
    
netcfg:
  devices:
    "device:sopnode-sw1":
      basic:
        managementAddress: "grpc://192.168.34.2:9559?device_id=1"
        driver: "stratum-bmv2"
        pipeconf: "org.stratumproject.fabric.bmv2"
        locType: "grid"
        gridX: 200
        gridY: 600