all:
  children:
    switches:
      hosts:
        sopnode-sw1-eth0.inria.fr:
          ansible_ssh_private_key_file: /workspaces/SLICES/sopnode/ansible/id_rsa_silecs
        sopnode-sw2-eth0.inria.fr:
          ansible_ssh_private_key_file: /workspaces/SLICES/sopnode/ansible/id_rsa_silecs
    controllers:
      hosts:
        sopnode-sw2-eth0.inria.fr:
          ansible_ssh_private_key_file: /workspaces/SLICES/sopnode/ansible/id_rsa_silecs