---
- name: Install k8s master
  hosts: masters
  become: yes
  environment:
    PATH: '{{ansible_env.PATH }}:/usr/local/bin/'

  roles:
    - role: k8s-master
    - role: k8s-ca-certificate

  post_tasks:
    - name: Wait for the node to be ready
      ansible.builtin.include_tasks: k8s-ready.yaml