---
- name: ONOS
  hosts: controllers
  remote_user: root
  tasks:
    - name: Start ONOS
      docker_container:
        name: onos
        image: onosproject/onos:2.7.0
        state: started
        restart: yes
        ports:
        - "8181:8181"
        - "8101:8101"
        - "5005:5005"
        - "830:830"
        tty: yes
        auto_remove: yes
        detach: yes
    - name: Activate Barefoot Drivers (may take up to 5 minutes)
      uri:
        url: http://{{ ansible_hostname }}:8181/onos/v1/applications/org.onosproject.drivers.barefoot/active
        user: onos
        password: rocks
        method: POST
      register: _result
      until: _result.status == 200
      retries: 30 # 30 * 10s = 300s = 5min
      delay: 10   # Every 10s

