---
# 5G config
GCN:
  namespace: blueprint
  core:
    present: true
    custom_files: blueprint/files
    custom_values: blueprint/values
  RAN:
    present: false
  UE:
    present: false
    tests:
      landmark_ping:
          landmark: google.fr