---
#ansible_user: root

#registry config
registry_name: registry-service
auth:
  - login: john
    password: doe
  - login: jane
    password: doe

# k8s config
k8s:
  runtime: docker #cri-o docker 
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.96.0.0/16
  dnsDomain: cluster.local
  calico:
    nodeAddressAutodetectionV4:
      cidrs:
        - 10.0.1.0/24
    encapsulation: VXLAN

# Stratum
stratum:
  mode: bmv2 #tofino
  bmv2_user: dsaucez

# Fabric
fabric:
  profile: fabric fabric-upf fabric-int fabric-upf-int # fabric

onos:
  image: onosproject/onos:2.5.8
  mode:  k8s # docker k8s
  applications:
    - name: org.onosproject.drivers.barefoot
    - name: org.onosproject.drivers.bmv2
    - name: org.onosproject.fpm 
    - name: org.onosproject.lldpprovider
    - name: org.onosproject.hostprovider
    - name: org.onosproject.dhcp
    - name: org.onosproject.proxyarp

netcfg:
  devices:
    device:leaf1:
      basic:
        name: leaf1
        managementAddress: grpc://10.0.1.4:9559?device_id=1
        driver: "stratum-bmv2"
        pipeconf: "org.stratumproject.fabric.bmv2"
        locType: grid
        gridX: 200
        gridY: 600
      segmentrouting:
        ipv4NodeSid: 101
        ipv4Loopback: 192.168.100.100
        routerMac: 00:AA:00:00:00:01
        isEdgeRouter: true
        adjacencySids: []
    device:leaf2:
      basic:
        name: leaf2
        managementAddress: grpc://10.0.1.2:9559?device_id=1
        driver: "stratum-bmv2"
        pipeconf: "org.stratumproject.fabric.bmv2"
        locType: grid
        gridX: 600
        gridY: 600
      segmentrouting:
        ipv4NodeSid: 102
        ipv4Loopback: 192.168.100.101
        routerMac: 00:AA:00:00:00:02
        isEdgeRouter: true
        adjacencySids: []
  ports:
    device:leaf1/2:
      interfaces:
      - name: leaf1-compute-1
        ips:
        - 192.168.100.202/24
        vlan-untagged: 100
    device:leaf1/1:
      interfaces:
      - name: leaf1-leaf2
        vlan-untagged: 100 
    device:leaf2/1:
      interfaces:
      - name: leaf2-leaf1
        vlan-untagged: 100
  apps:
    org.onosproject.dhcp:
      dhcp:
        ip: 192.168.100.217
        mac: de:ad:ca:fe:ca:ca
        subnet: 255.255.255.0
        broadcast: 192.168.100.255
        ttl: '63'
        lease: '300'
        renew: '150'
        rebind: '200'
        delay: '2'
        timeout: '150'
        startip: 192.168.100.60
        endip: 192.168.100.160