---
#registry config
registry_name: DATA+OMITTED
auth:
  - login: DATA+OMITTED
    password: DATA+OMITTED
  - login: DATA+OMITTED
    password: DATA+OMITTED
auth_file: DATA+OMITTED
path:
  certificate: DATA+OMITTED
  authentication: DATA+OMITTED

# k8s config
kube_config_local_path: DATA+OMITTED
master: DATA+OMITTED
subnet: DATA+OMITTED
