---
# 5G config
GCN:
  namespace: blueprint
  core:
    present: true
    custom_files: rocky/files     # directory where charts files are located, respect directory structure
    custom_values: rocky/values   # directory where values files are located, respect directory structure
  RAN:
    present: true
  UE:
    present: true
    tests:
      landmark_ping:
          landmark: google.fr