---
# 5G config
GCN:
  namespace: blueprint
  core:
    present: true
    custom_files: files     # directory where charts files are located, respect directory structure
    custom_values: values   # directory where values files are located, respect directory structure
  RAN:
    present: true
  UE:
    present: true
    tests:
      landmark_ping:
          landmark: google.fr