---
# k8s config
k8s:
  runtime: docker
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.96.0.0/16
  dnsDomain: cluster.local
  apiserver_advertise_address: 172.16.2.27
  calico:
    nodeAddressAutodetectionV4:
      cidrs:
        - 172.16.0.0/12
        #- 192.0.2.0/24
  encapsulation: VXLAN
# 5G config
GCN:
  namespace: blueprint
  RAN:
    present: true
    custom_files: blueprint/ran/files
    custom_values: blueprint/ran/values
  UE:
    present: true
    tests:
      landmark_ping:
          landmark: 172.22.10.1
