---
#ansible_user: root

#registry config
registry_name: registry-service
auth:
  - login: john
    password: doe
  - login: jane
    password: doe

# k8s config
k8s:
  subnet: 10.244.0.0/16

# calico config
calico:
  IP_AUTODETECTION_METHOD: interface=ma1

# Stratum
stratum:
  mode: tofino

# Fabric
fabric:
  profile: fabric fabric-upf fabric-int fabric-upf-int # fabric

onos:
  image: onosproject/onos:2.5.8
  mode:  docker #k8s
  applications:
    - name: org.onosproject.drivers.barefoot
    - name: org.onosproject.drivers.bmv2
    - name: org.onosproject.fpm 
    - name: org.onosproject.lldpprovider
    - name: org.onosproject.hostprovider
###    - name: org.onosproject.proxyarp

netcfg:
  devices:
    device:leaf1:
      basic:
        name: leaf1
        managementAddress: grpc://138.96.245.11:9559?device_id=1
        driver: stratum-tofino
        pipeconf: org.stratumproject.fabric-upf.mavericks_sde_9_7_0
        locType: grid
        gridX: 200
        gridY: 600
      segmentrouting:
        ipv4NodeSid: 101
        ipv4Loopback: 10.200.1.1
        routerMac: 00:AA:00:00:00:01
        isEdgeRouter: true
        adjacencySids: []
    device:leaf2:
      basic:
        name: leaf2
        managementAddress: grpc://138.96.245.13:9559?device_id=1
        driver: stratum-tofino
        pipeconf: org.stratumproject.fabric-upf.mavericks_sde_9_7_0
        locType: grid
        gridX: 600
        gridY: 600
      segmentrouting:
        ipv4NodeSid: 102
        ipv4Loopback: 10.200.1.2
        routerMac: 00:AA:00:00:00:02
        isEdgeRouter: true
        adjacencySids: []
    device:spine1:
      basic:
        name: spine1
        managementAddress: grpc://138.96.245.12:9559?device_id=1
        driver: stratum-tofino
        pipeconf: org.stratumproject.fabric-upf.montara_sde_9_7_0
        locType: grid
        gridX: 400
        gridY: 400
      segmentrouting:
        ipv4NodeSid: 201
        ipv4Loopback: 10.200.2.1
        routerMac: 00:BB:00:00:00:01
        isEdgeRouter: true
        adjacencySids: []
  ports:
    device:leaf1/100:
      interfaces:
      - name: leaf1-100
        ips:
        - 10.100.1.100/16
        vlan-untagged: 100
    device:leaf1/101:
      interfaces:
      - name: leaf1-101
        ips:
        - 10.100.1.101/16
        vlan-untagged: 100
    device:leaf1/102:
      interfaces:
      - name: leaf1-102
        ips:
        - 10.100.1.102/16
        vlan-untagged: 100
    device:leaf1/103:
      interfaces:
      - name: leaf1-103
        ips:
        - 10.100.1.103/16
        vlan-untagged: 100
    device:leaf1/200:
      interfaces:
      - name: leaf1-200
        ips:
        - 10.100.2.100/16
        vlan-untagged: 100
    device:leaf1/201:
      interfaces:
      - name: leaf1-201
        ips:
        - 10.100.2.101/16
        vlan-untagged: 100
    device:leaf1/202:
      interfaces:
      - name: leaf1-202
        ips:
        - 10.100.2.102/16
        vlan-untagged: 100
    device:leaf1/203:
      interfaces:
      - name: leaf1-203
        ips:
        - 10.100.2.103/16
        vlan-untagged: 100
    device:leaf1/300:
      interfaces:
      - name: leaf1-300
        ips:
        - 10.100.3.100/16
        vlan-untagged: 100
    device:leaf1/301:
      interfaces:
      - name: leaf1-301
        ips:
        - 10.100.3.101/16
        vlan-untagged: 100
    device:leaf1/302:
      interfaces:
      - name: leaf1-302
        ips:
        - 10.100.3.102/16
        vlan-untagged: 100
    device:leaf1/303:
      interfaces:
      - name: leaf1-303
        ips:
        - 10.100.3.103/16
        vlan-untagged: 100
    device:leaf2/100:
      interfaces:
      - name: leaf2-100
        ips:
        - 10.100.21.100/16
        vlan-untagged: 100
    device:leaf2/101:
      interfaces:
      - name: leaf2-101
        ips:
        - 10.100.21.101/16
        vlan-untagged: 100
    device:leaf2/102:
      interfaces:
      - name: leaf2-102
        ips:
        - 10.100.21.102/16
        vlan-untagged: 100
    device:leaf2/103:
      interfaces:
      - name: leaf2-103
        ips:
        - 10.100.21.103/16
        vlan-untagged: 100