---
- name: REGISTRY
  hosts: masters
  remote_user: root
  tasks:
    # Assuming that secrets were created before with
    #           kubectl create secret tls registry-service-secret --cert=registry-service.crt --key=registry-service.key
    #           kubectl create secret generic auth-secret --from-file=htpasswd
    - name: Deploy registry
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: registry
            namespace: default
            labels:
              app: registry
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: registry
            template:
              metadata:
                labels:
                  app: registry
              spec:
                volumes:
                  - name: certificates
                    secret:
                      secretName: registry-service-secret
                  - name: repo-vol
                    emptyDir: {}
                  - name: auth-vol
                    secret:
                      secretName: auth-secret
                containers:
                - name: registry
                  image: registry:2
                  env:
                  - name: REGISTRY_HTTP_ADDR
                    value: 0.0.0.0:443
                  - name: REGISTRY_HTTP_TLS_CERTIFICATE
                    value: /certs/tls.crt
                  - name: REGISTRY_HTTP_TLS_KEY
                    value: /certs/tls.key
                  - name: REGISTRY_AUTH
                    value: "htpasswd"
                  - name: REGISTRY_AUTH_HTPASSWD_REALM
                    value: "Registry Realm"
                  - name: REGISTRY_AUTH_HTPASSWD_PATH
                    value: "/auth/htpasswd"
                  ports:
                  - containerPort: 443
                  volumeMounts:
                    - name: certificates
                      mountPath: /certs
                    - name: repo-vol
                      mountPath: /var/lib/registry
                    - name: auth-vol
                      mountPath: "/auth"
                      readOnly: true

    - name: Deploy registry-service
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: registry-service
            namespace: default
          spec:
            selector:
              app: registry
            ports:
            - protocol: TCP
              port: 443
              targetPort: 443