---
- name: ONOS
  hosts: controllers
  remote_user: root
  tasks:
    # Assuming creation of the secret with kubectl create secret tls registry-service-secret --cert=registry-service.crt --key=registry-service.key
    - name: Deploy registry
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: registry
            namespace: onos-ns
            labels:
              app: registry
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: registry
            template:
              metadata:
                labels:
                  app: registry
              spec:
                volumes:
                  - name: certificates
                    secret:
                      secretName: registry-service-secret
                containers:
                - name: onos
                  image: registry:2
                  env:
                  - name: REGISTRY_HTTP_ADDR
                    value: 0.0.0.0:443
                  - name: REGISTRY_HTTP_TLS_CERTIFICATE
                    value: /certs/tls.crt
                  - name: REGISTRY_HTTP_TLS_KEY
                    value: /certs/tls.key
                  ports:
                  - containerPort: 443
                  volumeMounts:
                    - name: certificates
                      mountPath: /certs

    - name: Deploy registry-service
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: registry-service
            namespace: onos-ns
          spec:
            selector:
              app: registry
            ports:
            - protocol: TCP
              port: 443
              targetPort: 443