---
- name: Stop running stratum instance
  become: yes
  community.docker.docker_container:
    name: stratum-container
    state: absent
- block:
  - name: starting the stratum container
    shell: "~/stratum/setup_dev_env.sh -- --privileged -d --network=host --name stratum-container"

  - name: Check if stratum already been built
    stat:
      path: ~/stratum/stratum_bmv2_deb.deb
    register: stat_result

  - name: Build stratum
    import_tasks: 'bmv2_stratum_build.yaml'
    when: not stat_result.stat.exists

  - name: Install stratum
    ansible.builtin.shell: 'sudo apt-get install -y --reinstall ~/stratum/stratum_bmv2_deb.deb'

  - name: Start stratum
    ansible.builtin.shell: sudo nohup stratum_bmv2 -chassis_config_file=/etc/stratum/chassis_config.pb.txt 2>1&  sleep 2

  become: yes
  become_user: '{{ stratum.bmv2_user }}'
