---
- name: Set user rights
  ansible.builtin.shell: "chown {{ ansible_user }} {{ ansible_env.HOME }}/.cache"
  become: yes
  become_user: 'root'

- block:
  - name: Build stratum
    community.docker.docker_container_exec:
      container: stratum-container
      command: "bazel build //stratum/hal/bin/bmv2:stratum_bmv2_deb"

  - name: Copy the built stratum package
    community.docker.docker_container_exec:
      container: stratum-container
      command: "cp -f /stratum/bazel-bin/stratum/hal/bin/bmv2/stratum_bmv2_deb.deb /stratum/stratum_bmv2_deb.deb"

  become: yes
  become_user: '{{ stratum.bmv2_user }}'