---
- name: Build stratum
  community.docker.docker_container_exec:
    container: stratum-container
    command: "bazel build //stratum/hal/bin/bmv2:stratum_bmv2_deb"

- name: Copy the built stratum package
  community.docker.docker_container_exec:
    container: stratum-container
    command: "cp -f /stratum/bazel-bin/stratum/hal/bin/bmv2/stratum_bmv2_deb.deb /stratum/stratum_bmv2_deb.deb"