---
- name: Retrieve stratum
  ansible.builtin.git:
    repo: https://github.com/stratum/stratum.git
    dest: ~/stratum/
    version: 29f391580de8d5ee2d7a207a9a4261fda4e54a6f #2022-06-30
    force: yes

- name: Copy chassis config
  ansible.builtin.copy:
    src: "chassis_config/{{ inventory_hostname }}/chassis_config.pb.txt"
    dest: /tmp/chassis_config.pb.txt
    force: yes
  register: custom_stratum_chassis_config
  ignore_errors: true

- name: Instantiate Stratum
  import_tasks: '{{ stratum.mode }}_stratum.yaml'
