---
- name: Retrieve stratum
  become: yes
  ansible.builtin.git:
    repo: https://github.com/stratum/stratum.git
    dest: ~/stratum/
    version: e2640fc
    force: yes

- name: Instantiate Stratum
  import_tasks: '{{ stratum.mode }}_stratum.yaml'